# Generated by Django 4.1 on 2022-10-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_alter_tomeet_date_of_meeting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tomeet',
            name='comment',
        ),
        migrations.AlterField(
            model_name='tomeet',
            name='phone_number',
            field=models.IntegerField(default=0),
        ),
    ]
