# Generated by Django 4.1 on 2022-10-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0004_alter_tomeet_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tomeet',
            name='comment',
            field=models.TextField(default='text'),
        ),
    ]
