# Generated by Django 4.1 on 2022-10-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0005_tomeet_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('done_for_today', models.TextField(default='')),
                ('important', models.TextField(default='')),
                ('comment', models.TextField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='tomeet',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
